# -*- coding: utf-8 -*-
"""exploratory data analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lh-EYOu2wDMAtMkfGhCVqFpWzzjIOX9j
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('/content/samplebankloandata.csv')
print(df.head(20))

print(df.isnull().sum())

print(df.dtypes)

print(df.describe())

sns.histplot(data=df, x='total_pymnt',kde=True)
plt.title('Distribution of Total Payment')
plt.show()

sns.countplot(data=df,x='purpose')
plt.xticks(rotation=45)
plt.title('Purpose of Bank Loan')
plt.show()

sns.barplot(data=df,x='purpose',y='interest_rate',estimator=np.mean)
plt.xticks(rotation=45)
plt.title('Average Interest Rate')
plt.show()

plt.pie(df['region'].value_counts(),labels=df['region'].value_counts().index,autopct='%1.1f%%')
plt.title('Loan Distribution by Region')
plt.show()

sns.boxplot(data=df,x='home_ownership',y='final_d',showfliers=False)
plt.title('home ownership by final date ')
plt.show()

df['purpose']=df['purpose']
df.groupby('purpose')['loan_amount'].sum().plot()
plt.title('Purpose and Loan Amount')
plt.xticks(rotation=45)
plt.show()

sns.scatterplot(data=df, x='annual_inc', y='loan_amount')
plt.title('Annual income vs. Loan amount')
plt.show()

variables_of_interest = ['annual_inc', 'loan_amount', 'interest_rate', 'dti']
subset_df = df[variables_of_interest]
corr = subset_df.corr()
sns.heatmap(corr, annot=True, cmap='Blues')
plt.title('Correlation Heatmap')
plt.show()

import plotly.express as px
fig = px.scatter_3d(df, x='annual_inc', y='loan_amount', z='term',color='application_type')
fig.update_layout(scene = dict(
                    xaxis = dict(title  = 'Annual Income'),
                    yaxis = dict(title  = 'Loan Amount'),
                    zaxis = dict(title  = 'term')))
fig.show()